version: '3.8'

services:
  telegram-bot:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/app/logs:rw
    environment:
      - TZ=Europe/Moscow
    networks:
      - bot-network
    # Ограничения ресурсов
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Безопасность
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    # Health check
    healthcheck:
      test: ["CMD", "python3", "docker/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  bot-network:
    driver: bridge
